### ISSUE TITLE
음식 수량 다양하게 하기

### ISSUE THREAD

**Issue by dasd412** [dasd412/RemakeDiabetesDiaryAPI#36]
double amount 말고도 
```
Enum AmountUnit {
 GRAM, KG
}
```
등으로 Food 엔티티의 속성으로 넣는 것이 좋아보인다.

브라우저 단에는 
[텍스트 박스 ][셀렉트 박스]
로 표시하고.

**Comment by dasd412** [comment]
음식 수량 단위라는 속성을 js에 추가한 후 다음과 같은 에러가 발생하였다.
```
jquery-3.6.0.js:4050 jQuery.Deferred exception: Cannot read properties of undefined (reading 'add') TypeError: Cannot read properties of undefined (reading 'add')
    at Object.cacheAddFoods (http://localhost:8084/js/post/post.js:92:39)
    at HTMLDivElement.<anonymous> (http://localhost:8084/js/update_delete/update_delete.js:99:33)
    at Function.each (http://localhost:8084/vendor/vendor/jquery/jquery-3.2.1.min.js:2:2715)
    at r.fn.init.each (http://localhost:8084/vendor/vendor/jquery/jquery-3.2.1.min.js:2:1003)
    at HTMLLIElement.<anonymous> (http://localhost:8084/js/update_delete/update_delete.js:94:46)
    at Function.each (http://localhost:8084/vendor/vendor/jquery/jquery-3.2.1.min.js:2:2715)
    at r.fn.init.each (http://localhost:8084/vendor/vendor/jquery/jquery-3.2.1.min.js:2:1003)
    at Object.makeOriginFoodData (http://localhost:8084/js/update_delete/update_delete.js:88:27)
    at Object.init (http://localhost:8084/js/update_delete/update_delete.js:111:14)
    at HTMLDocument.<anonymous> (http://localhost:8084/js/update_delete/update_delete.js:228:29) undefined
```

```
jquery-3.6.0.js:4059 Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at Object.cacheAddFoods (post.js:92:39)
    at HTMLDivElement.<anonymous> (update_delete.js:99:33)
    at Function.each (jquery-3.2.1.min.js:2:2715)
    at r.fn.init.each (jquery-3.2.1.min.js:2:1003)
    at HTMLLIElement.<anonymous> (update_delete.js:94:46)
    at Function.each (jquery-3.2.1.min.js:2:2715)
    at r.fn.init.each (jquery-3.2.1.min.js:2:1003)
    at Object.makeOriginFoodData (update_delete.js:88:27)
    at Object.init (update_delete.js:111:14)
    at HTMLDocument.<anonymous> (update_delete.js:228:29)
```

**Comment by dasd412** [comment]
해당 에러가 발생하는 곳은 수정 및 삭제 폼이다.

**Comment by dasd412** [comment]
원인을 찾아보니 간단했다.
post.js에선 amountUnit을 추가했지만, update-delete.js에선 해당 속성을 추가하지 않은 것이다.
post.js의 코드는 다음과 같다.
```
cacheAddFoods: function (liId, foodName, foodAmount, foodAmountUnit, mealKey) {}
```
기존 update-delete.js에선 다음과 같이 호출하고 있었다.
```
 PostManipulator.cacheAddFoods(liId, foodName, amount, eatTime);
``

즉 함수를 찾지 못해서 생긴 당연한 일이었다.

**Comment by dasd412** [comment]
해당 에러는 해결이 되었다. 
하지만, 속성 하나를 추가하기 위해서 update-delete.js만 해도 다섯 라인을 손 봐야 했다.
추후 리팩토링이 필요하다.
